/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route } from './routes/__root'
import { Route } from './routes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})







module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/'
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute
      parentRoute
const rootRouteChildren= {
  IndexRoute= rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()

import} from './router.tsx'
import} from './start.ts'
module '@tanstack/react-start' {
  interface Register {
    ssr
    router
    config
